spring.application.name=citas


spring.datasource.url=jdbc:postgresql://ep-empty-sky-aqmg9k1y-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_l70dBFxZOQTg
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

pacientes.service.url=${PACIENTES_URL:http://localhost:8085}
auth.service.url=${AUTH_URL:http://localhost:8083}
server.port=${PORT:8089}