spring.application.name=citas
server.port=8089

spring.datasource.url=jdbc:postgresql://ep-empty-sky-aqmg9k1y-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_l70dBFxZOQTg
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true